### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by vankasteelj** [alxhotel/opensubtitles-js#1]
It would be more fitting to use the original GPL license instead of rebranding to MIT like if you wrote this code. Not cool bro.

**Comment by alxhotel** [comment]
You are very right, sir. I apologize.

License is now changed to GPL. README, LICENSE and package.json updated.

Let me know if I should fix anything more related to the license.

Thanks ;)

**Comment by vankasteelj** [comment]
Nope, it's all good, thanks for the original author!
